neos/Neos.EventSourcing

- Classes/Domain/AggregateRootInterface.php
- Classes/Domain/AggregateRootTrait.php
This change introduce a second parameter for the recordThat method to allow setting metadata to the EventTransport object.
> TASK: Improve metadata handling

- Classes/Domain/AbstractAggregateRoot.php
- Classes/Domain/AggregateRootInterface.php
- Classes/Event/AbstractAggregateEvent.php
- Classes/Event/AggregateEventInterface.php
This changes the behaviour of recordThat() and the EventInterface.
With this change applied, you don't have to specify the aggregate identifier anymore when calling `recordThat()`. A new interface and abstract class for events provides a getter and setter for the aggregate identifier and makes sure that an identifier can't be changed once it has been set.
Example:
```php
/**
* Create a new organization
*
* @param string $name
* @param string $slug
* @param string $primaryOwnerUserIdentifier Identifier of the primary owner user for the new organisation
* @return static
*/
static public function create($name, $slug, $primaryOwnerUserIdentifier)
{
$instance = new static();
$instance->recordThat(new OrganizationHasBeenCreated($name, $slug, $primaryOwnerUserIdentifier));
return $instance;
} …
```
> TASK: recordThat() sets aggregate id on event

- Classes/Domain/AbstractAggregateRoot.php
- Classes/Domain/AbstractEventSourcedAggregateRoot.php
- Classes/EventStore/EventSourcedRepository.php
Adjusts the `AbstractAggregateRoot` to expect an `aggregateIdentifier` in the (protected) constructor.
The aggregate instanciation can be done with an overridden constructor or, preferably, with a static method:
static public function create(string $aggregateIdentifier, string $someParam) : SomeAggregate {
$aggregate = new SomeAggregate($aggregateIdentifier);
$aggregate->recordThat(
new SomeAggretateWasCreated(
$someParam
)
);
}
Resolves: #46
> TASK: Handle Aggregate Identifier in Framework

- Classes/Domain/AbstractAggregateRoot.php
- Classes/Domain/AbstractEventSourcedAggregateRoot.php
- Classes/Domain/AggregateRootInterface.php
- Classes/EventStore/EventSourcedRepository.php
- Readme.md
This change renames all usages of "aggregate identifier"
to just "identifier" where the context is clear.
Resolves: #49
> TASK: Rename aggregate identifier to identifier

- Classes/Domain/AbstractAggregateRoot.php
- Classes/Domain/AggregateRootInterface.php
This change allows for aggregates to record events that do not
implement the `AggregateEventInterface`.
Resolves: #51
> FEATURE: Allow aggregates to handle identifiers

- Classes/Projection/Doctrine/AbstractDoctrineProjector.php
- Classes/Projection/Doctrine/DoctrineProjectionPersistenceManager.php
Previously the `Finder` had to be used within doctrine projectors in order to *update* a read model.
This was not only error prone and cumbersome but didn't support retrieval of not yet persisted
objects because of the missing identity map.
Previously:
```php
/**
* @Flow\Inject
* @var SomeFinder
**/
protected $someFinder;
public function whenSomethingHappened(SomethingHappened $event) {
$readModel = $this->someFinder->findOneByIdentifier($event->getIdentifier());
// ...
}
```
Now:
```php
public function whenSomethingHappened(SomethingHappened $event) {
$readModel = $this->get($event->getIdentifier());
// ...
}
```
Related: #13
> FEATURE: Allow retrieval of read model instances in doctrine projectors

- Classes/EventStore/EventSourcedRepository.php
- Classes/EventStore/EventStreamResolver.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/StreamNameResolver.php
Previously the stream name had the format
`<AggregateClassName>::<AggregateIdentifier>` hard-coding the fully qualified
class name into the persisted stream.
With this change the stream name format is changed to:
`<BoundedContext>:<ShortAggregateClassName>:<AggregateIdentifier>` (lowercased)
Where "BoundedContext" defaults to the Package Key of the aggregate.
Example:
`Some.PackageKey:SomeAggregate:<UUID>`
Furthermore this changes the persisted event type from
`<EventClassName>`
to
`<BoundedContext>:<ShortEventType>`.
This is also the first step to allow 3rd party code to hook into the mapping
i.e. in order to up-cast event types.
Related: #36
> TASK: Use generic designators for stream & event names

- Classes/Domain/RepositoryInterface.php
- Classes/EventStore/EventSourcedRepository.php
The `Repository` can only be used for `EventSourcedAggregateRootInterface`
instances.
This change adjusts the signature respectively.
> BUGFIX: Fix signature of `RepositoryInterface`

- Classes/EventStore/AbstractEventSourcedRepository.php
Besides this marks the two API method `final`.
> BUGFIX: Fix naming of abstract `EventSourcedRepository`

- Classes/Domain/AbstractAggregateRoot.php
- Classes/Event/EventTypeResolver.php
- Classes/EventListener/EventListenerLocator.php
Previously the "event type" was used to resolve the `when*()` method names
of event listeners.
Currently the event type is equal to the short event class name, but this
had some drawbacks:
* We need an instance of the `EventTypeResolver` in the aggregate
* It wasn't possible to map an event type to a different method
This commit also fixes the package key prefixing!
Resolves: #63
> TASK: Use the event class name to resolve listener

- Classes/Domain/AbstractAggregateRoot.php
- Classes/Domain/AbstractEventSourcedAggregateRoot.php
- Classes/Domain/EventSourcedAggregateRootInterface.php
- Classes/EventStore/EventSourcedRepository.php
This turns `AggregateRoot::reconstituteFromEventStream()` into a static
factory method that class the protected constructor.
This way we can ommit the `unserialize()` trick and ensure consistency.
Resolves: #67
> TASK: Static factory method for aggregate roots

- Classes/Event/EventTypeResolver.php
This fixes an issue with the EventTypeResolver which would
not compile when Flow is run in Production context.
Closes #71
> BUGFIX: Fix EventTypeResolver for Production

- Classes/EventListener/EventListenerLocator.php
This fixes another issue with the EventListenerLocator
which doesn't compile in Production.
Closes #71 (again)
> BUGFIX: EventListenerLocator does not compile

- Classes/Command/ProjectionCommandController.php
- Classes/Projection/Doctrine/AbstractDoctrineProjector.php
- Classes/Projection/ProjectionManager.php
- Classes/Projection/ProjectorInterface.php
Before replaying events for a projection, the projection data
is now dropped.
This introduces a new method `reset()` to the `ProjectorInterface`.
Closes #81
> !!! FEATURE: Drop projection data before replay

- Classes/Command/ProjectionCommandController.php
- Classes/EventListener/EventListenerLocator.php
- Classes/Projection/Projection.php
- Classes/Projection/ProjectionManager.php
This stabilizes the two `compileStatic` functions ``EventListenerLocator::detectListeners()``
and ``ProjectionManager::detectProjectors()`` so that they don't rely on other 3rd party instances
(see #71).
As a side-effect this moves the "shortest unambiguous identifier" determination from the ``ProjectionManager``
to the corresponding CLI Controller as discussed in #95.
Related: #71
> TASK: Simplify statically compiled functions

- Classes/Domain/RepositoryInterface.php
- Classes/EventStore/AbstractEventSourcedRepository.php
This change renames `findByIdentifier()` to `get()`.
Closes #80
> !!! TASK: Rename AbstractEventSourcedRepository->findByIdentifier()

- Classes/Command/ProjectionCommandController.php
- Classes/Event/EventPublisher.php
- Classes/EventListener/AsyncEventListenerInterface.php
- Classes/EventListener/AsynchronousEventListenerInterface.php
- Classes/EventListener/EventListenerLocator.php
- Classes/EventStore/EventStreamFilterInterface.php
- Classes/EventStore/EventTypesFilter.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/StreamNameFilter.php
- Classes/Projection/ProjectionManager.php
Usage:
In your projector implement the new AsynchronousEventListenerInterface for example:
class SomeProjector extends AbstractDoctrineProjector implements AsynchronousEventListenerInterface
{
...
}
Now this projector will be skipped during default event publishing and you can trigger a manual catchup via
flow projection:catchup
Handling of "generic" async `EventListeners` will be tackled in a separate pull request
> Feature: Asynchronous events

- Classes/Command/ProjectionCommandController.php
- Classes/Projection/InvalidProjectionIdentifierException.php
- Classes/Projection/ProjectionManager.php
a `try/catch` block catching any `\Exception` is dangerous because
it disables exception logging and can disguise nested exceptions.
> BUGFIX: Don't catch all exceptions in projection CLI

- Classes/Command/ProjectionCommandController.php
- Classes/EventStore/EventStreamResolver.php
- Classes/EventStore/StreamNameResolver.php
- Classes/Projection/ProjectionManager.php
The Package Manager's method `getPackageByClassName()` is deprecated
and will be removed in Flow 4.0.
This change replaces some calls to this deprecated method.
Fixes: #86
> BUGFIX: Replace calls to deprecated `getPackageByClassName()`

- Classes/Domain/AbstractEventSourcedAggregateRoot.php
- Classes/EventStore/EventStream.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
Previously the `EventStream` had a version, but this only
makes sense for aggregate streams.
For different partitioned streams (e.g. for projections or
other event listeners) this version is misleading because it
just contains the highest version within the many streams.
Note:
We could replace the version with the last *sequence number*
but currently that's not needed and without that we are still
free to implement actual streams that stay open.
> BUGFIX: Don't store "version" in the EventStream

- Classes/Event/EventPublisher.php
- Classes/EventStore/RawEvent.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/Storage/Doctrine/DoctrineStreamIterator.php
- Classes/EventStore/Storage/Doctrine/Schema/EventStoreSchema.php
- Classes/EventStore/WritableEvent.php
This consistently renames "id" to "sequenceNumber" where applicable
and adds a new property "identifier" to `WritableEvent` and `RawEvent`
that will be set to a UUID during event publishing.
This allows for correlation and de-duplication of events in respective
handlers.
Note:
With this change it's not yet possible to *set* the event identifier from
the application.
Related: #6
> !!! FEATURE: Unique event identifiers

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/Storage/Doctrine/DoctrineStreamIterator.php
This adjusts the `DoctrineStreamIterator` so that it always fetches
at most 100 events at once from the database.
Background:
`QueryBuilder::execute()` behaves differently than it's `\PDO` counter
part in that it always fetches the whole result set immediately.
For projections with lots of events this will exceed the memory limit.
Fixes: #96
> BUGFIX: Don't fetch all events at once

- Classes/Command/ProjectionCommandController.php
- Classes/Projection/ProjectionManager.php
Adds a `verbose` flag to the CLI commands `projection:replay`,
`projection:replayall` and `projection:catchup` that, if specified,
displays a progress bar for handled events.
This is especially useful for replaying projections with a lot of
events.
> FEATURE: Progress bar for projection related CLI commands

- Classes/Event/EventTypeResolver.php
- Classes/Event/ProvidesEventTypeIdentifierInterface.php
- Classes/Event/ProvidesEventTypeInterface.php
- Readme.md
This change introduces a new optional interface for event implementations
which allows for overriding the event type identifier convention for the
event class to event type mapping.
This feature, for example, allows for implementing an event class which
represents a remote event.
> FEATURE: Custom event type identifier mapping

- Classes/Command/EventStoreCommandController.php
This change introduces a little CLI command which provides some
basic connection information for the Event Store. Right now
this command only serves for quickly testing the connection.
> FEATURE: Simple CLI command for Event Store status

- Classes/EventStore/EventStream.php
This change configures the property mapper to ignore unknown
properties from the source (serialized event) when mapping
them to the event class.
It only will show an effect in combination with  a new core feature:
https://github.com/neos/flow-development-collection/pull/883
Addresses #94
> FEATURE: Skip unknown properties when mapping events

- Classes/Event/EventTypeResolver.php
Implementations of `ProvidesEventTypeInterface` might also be prone to duplicate event types
> TASK: Throw exception on duplicate event mapping from ProvidesEventTypeInterface

- Classes/ProcessManager/AbstractProcessManager.php
This change allows the anonymous function in a process manager
configuration to access the RawEvent, similar like the event handler
method can.
> TASK: Pass RawEvent to process manager configuration

- Readme.md
This brings the readme in line with the current state of implementation and conceptual consensus and slightly restructures it into a logical read order:
- start with basic information how a project can be structured
- explain the write side through it's API (commands + events)
- show a sample implementation of a `CommandHandler` to separate the entry point (web/cli) from the command handling logic (tbd: an implementation of a CommandHandler without using an Aggregate)
- explain how (hard) business constraints can be modelled with Aggregates (tbw)
- explain how business processes can be modelled with ProcessManagers (tbw)
- explain the read side conceptually via Projector, Finder and Read Model
- show how a Projection can be made asynchronous via `AsynchronousEventListenerInterface` (tbw) …
> TASK: Update and restructure Readme

- Classes/Command/EventStoreCommandController.php
- Classes/Event/EventPublisher.php
- Classes/EventListener/EventListenerLocator.php
- Classes/EventStore/AbstractEventSourcedRepository.php
- Classes/EventStore/EventStore.php
- Classes/EventStore/EventStoreManager.php
- Classes/EventStore/Exception/StorageConfigurationException.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/Storage/Doctrine/Factory/ConnectionFactory.php
- Classes/EventStore/Storage/EventStorageInterface.php
- Classes/Projection/ProjectionManager.php
- Configuration/Objects.yaml
- Configuration/Settings.yaml
- Tests/Unit/EventStore/EventStoreManagerTest.php
This feature allows multiple Event Store backends to be used within the same Flow installation.
With that it's possible to use separate database tables or completely different backends for certain event types.
When using the provided `DoctrineEventStorage` backend, the database connection options is now merged with the Flows default persistence backend options.
As a result the `default` Event Store uses the same DB connection circumventing #42.
In order to store events from a package `Some.Package` to a different database table, that's all you need to configure:
```yaml
Neos:
EventSourcing:
EventStore:
stores:
'someCustomStore':
boundedContexts:
'Some.Package': true
storage: 'Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage'
storageOptions:
eventTableName: …
```
> FEATURE: Support for multiple Event Store backends

- Classes/EventStore/Storage/Doctrine/Factory/ConnectionFactory.php
When using the new `eventstore::setup*` command(s) introduced
with #138 in a Neos installation an exception was thrown:
Unknown column type "flow_json_array" requested.
Reason for this is the `EntityManagerConfiguration::enhanceEntityManager`
slot that is only invoked if the `EntityManager` is acutally used.
This patch fixes that by injecting the Doctrine `ObjectManager` to
the `ConnectionFactory` so that the signal is fired.
Related: #55
> BUGFIX: Fix EntityMananger initialization

- Classes/Projection/Doctrine/AbstractDoctrineProjector.php
- Classes/Projection/Doctrine/DoctrineProjectionPersistenceManager.php
This introduces a `createQuery()` method for the `AbstractDoctrineProjector`
which allows for finding entries in event listeners of the concrete
projector.
Note that, especially during a projection replay, earlier changes might
not yet be persisted by Doctrine and thus can't be found by a query.
You will need to persist changes manually with `$this->projectionPersistenceManager->persistAll();`
in these cases.
Closes #136
> FEATURE: Introduce createQuery for Doctrine Projector

- Classes/EventListener/EventListenerLocator.php
When trying to replay a projection and the corresponding
projector doesn't contain any Listener methods a misleading
exception was thrown.
This patch fixes this by detecting empty Listeners in the
`EventListenerLocator` and displaying a more meaningful
error in that case.
Fixes: #145
> BUGFIX: Detect EventListeners without listener methods

- Classes/Projection/ProjectorInterface.php
That method is only used by (and only makes sense for) the `AbstractDoctrine`
that needs it to create the DQL query based upon an entity.
The state of custom projectors might consist of many entities - or none at all.
> TASK: Remove `getReadModelClassName()` method from `ProjectorInterface`

- Classes/Event/EventPublisher.php
- Classes/EventStore/EventStream.php
- Classes/Property/AllowAllPropertiesPropertyMappingConfiguration.php
This fixes issues with nested value objects where a fixed hierarchy
for a property mapping configuration does not work.
> BUGFIX: Recursively allow all properties when converting events

- Classes/Event/EventPublisher.php
- Classes/Event/EventWithMetadata.php
- Readme.md
This change provides a simple and straight-forward way to specify metadata
along with an event when it is published.
In order to specify the metadata, simply wrap the event to be published with
and `EventWithMetadata` object and set the metadata there. This wrapper object
can be published like a normal even using `publish()` or `publishMany()`.
> FEATURE: Events with metadata

- Classes/Event/EventWithMetadata.php
- Tests/Unit/Event/EventWithMetadataTest.php
Previously when nesting two or more `EventWithMetadata` instances
the outer most would override the metadata of the others.
This is fixed with this change.
It also adds unit tests for the new class.
Related: #152
> FEATURE: Allow EventWithMetadata to be nested

- composer.json
This package required PHP `>= 7.0.1` which will conflict with a platform
dependency of `7.0`:
```
{
// ...
"config": {
"platform": {
"php": "7.0"
}
}
```
> TASK: Relax PHP version constraint

- Classes/EventStore/RawEvent.php
Adds a `@Flow\Proxy(false)` annotation to the `RawEvent` DTO
in order to make it serializable.
> TASK: Prevent `RawEvent` from being proxied

- Classes/EventStore/RawEvent.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/Storage/Doctrine/DoctrineStreamIterator.php
Makes the `streamName` of a given event accessible via `RawEvent::getStreamName()`.
This can be useful for debugging purposes and is a precondition for #164
Related: #164
> FEATURE: Expose `streamName` in `RawEvent`

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/Storage/Doctrine/DoctrineStreamIterator.php
Adds the `ping` => `close` => `connect` reconnection logic
(as suggested by Doctrine) to the `DoctrineEventStorage` to
prevent connection timeouts to occur for long running
processes.
Fixes: #171
> BUGFIX: Reconnect database connection if it timed out

- Classes/Domain/AbstractAggregateRoot.php
Currently aggregate roots are unable to record events with metadata. 
This change will unwrap those events before the respective handler function is executed.
> BUGFIX: Unwrap event before executing handler

- Classes/TypeConverter/EventToArrayConverter.php
PHP's DATE_ISO8601 is defined as `"Y-m-d\\TH:i:sO"` while for converting a value to DateTime object, the Flow DateTimeConverter expects `\DateTime::W3C` by default, which uses the more widely accepted and used `"Y-m-d\TH:i:sP"`.
See http://php.net/manual/en/class.datetimeinterface.php#datetime.constants.iso8601 (Note that ATOM is the same as W3C)
See https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Property/TypeConverter/DateTimeConverter.php#L75
Related to #181
> TASK: Change format for DateTimeInterface values to match `DateTimeConverter`

- Classes/Projection/Doctrine/DoctrineProjectionPersistenceManager.php
DoctrineEntityManager was already used for the property typehint. The `ObjectManager` is deprecated though and should be replaced with `EntityManagerInterface`.
See https://github.com/neos/flow-development-collection/pull/1272
> TASK: Use correct typehint for doctrine EntityManager

- Classes/EventListener/EventListenerInvoker.php
As suggested by @skurfuerst  in https://github.com/neos/Neos.EventSourcing/pull/196
> Release highest applied sequence number in finally block

- Classes/EventListener/EventListenerInvoker.php
#199 introduced a regression that prevents event listeners
including projections to be replayed correctly if no event
has been published to the corresponding stream yet.
> BUGFIX: Catchup with empty stream leads to an exception

- Classes/EventStore/EventStoreManager.php
Fixes `EventStoreManager::getEventStoreForEventListener()` to return
the default Event Store instance if the package could not be determined
> BUGFIX: Stabilize EventStoreManager::getEventStoreForEventListener()

- Classes/EventStore/Normalizer/ValueObjectNormalizer.php
- Tests/Unit/EventStore/Normalizer/Fixture/ArrayBasedValueObject.php
- Tests/Unit/EventStore/Normalizer/Fixture/BooleanBasedValueObject.php
- Tests/Unit/EventStore/Normalizer/Fixture/FloatBasedValueObject.php
- Tests/Unit/EventStore/Normalizer/Fixture/IntegerBasedValueObject.php
- Tests/Unit/EventStore/Normalizer/Fixture/StringBasedValueObject.php
- Tests/Unit/EventStore/Normalizer/ValueObjectNormalizerTest.php
When it comes to "int", "bool" and "float" there's a missmatch between
the PHP `gettype()`  method result and the reflection property type.
One results "integer, boolean, double", the other "int, bool, float".
Those named constructor arguments are supported:
```
IntegerBasedValueObject::fromInteger(int $value): self
StringBasedValueObject::fromString(string $value): self
BooleanBasedValueObject::fromBoolean(bool $value): self
FloatBasedValueObject::fromFloat(float $value): self
ArrayBasedValueObject::fromArray(array $value): self
```
Related: https://github.com/neos/Neos.EventSourcing/issues/210
> BUGFIX: Fix normalization for integer, boolean and float based value objects

- Classes/EventBus/EventBus.php
- Classes/EventListener/AppliedEventsLogRepository.php
- Classes/Projection/ProjectionManager.php
Replaces `ensureHighestAppliedSequenceNumbersAreInitialized()` by a method
`initializeHighestAppliedSequenceNumber()` that has to be called per listener
in order to inverse dependencies
> TASK: Refactor AppliedEventsLogRepository initialization

- Classes/EventStore/EventStoreManager.php
- Configuration/Objects.yaml
To simplify basic usage this change introduces a basic `Objects.yaml`
configuration that allows for injecting the configured "default" `EventStore`
without having to use the `EventStoreManager`.
Usage:
```php
<?php
// ...
/**
* @Flow\Inject
* @var EventStore
*/
protected $eventStore;
```
This change is fully backwards compatible as the `EventStoreManager` can still
be used to get hold of a specific Event Store instance (for now).
And obviously one can rewire the automatic injection via some custom `Objects.yaml` like:
```yaml
Some\Package\Some\Class:
properties:
'eventStore':
object:
factoryObjectName: Neos\EventSourcing\EventStore\EventStoreManager
factoryMethodName: getEventStore
arguments:
1:
value: 'some-other-event-store'
```
Related: #212
> FEATURE: Allow default EventStore to be injected

- Classes/EventStore/EventNormalizer.php
- Classes/EventStore/Normalizer/ValueObjectNormalizer.php
- Tests/Functional/EventStore/EventNormalizerTest.php
- Tests/Functional/EventStore/Fixture/MockDomainEvent3.php
- Tests/Functional/EventStore/Fixture/MockValueObject.php
- Tests/Unit/EventStore/EventNormalizerTest.php
- Tests/Unit/EventStore/Fixture/ArrayBasedEvent.php
- Tests/Unit/EventStore/Normalizer/Fixture/InvalidArrayBasedValueObject.php
- Tests/Unit/EventStore/Normalizer/ValueObjectNormalizerTest.php
Adjusts the `ValueObjectNormalizer` so that it requires a class
to implement a named constructor `fromArray(array $data)` when
denormalizing array data.
Fixes: #233
> !!! BUGFIX: Fix (de)normalization for array based classes

- Classes/EventListener/EventListenerInvoker.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/Projection/Doctrine/DoctrineProjectionPersistenceManager.php
Replaces `catch (\Exception)` by `catch (\Throwable)` for fail-safe roll backs
Fixes: #242
> BUGFIX: Catch all throwables

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
Based on #237 i would suggest a solution like this. Currently the schema is generated without any configuration and this adds a SchemaConfig with the default flow config for databases.
> Apply default db-config on createSchema

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
A follow up to #245 fixing the `DoctrineEventStorage` so that it
actually exits the retry-loop when successful (*doh).
This fix also makes sure that the transaction is rolled back when
the `verifyExpectedVersion()` call failed
> BUGFIX: Follow-up

- Classes/EventStore/Normalizer/ValueObjectNormalizer.php
This drastically increase performance for large set of events
that uses valueObjects in the constructor.
> FEATURE: Add first level cache in ValueObjectNormalizer

- composer.json
Add the possibility to use the 1.0 version of Neos.EventSourcing with Flow 6.x.
> Add Flow 6.x to compatible Flow versions

- composer.json
Reverts neos/Neos.EventSourcing#254 since 1.0 is not compatible with Flow 6.0 yet (see comments in #254)
> Revert "Add Flow 6.x to compatible Flow versions"

- Classes/EventPublisher/DefaultEventPublisherFactory.php
Fixes `DefaultEventPublisherFactory::create()` to return the same
`EventPublisherInterface` instance for a given `$eventStoreIdentifier`.
This allows for injecting Event Publishers into 3rd party code with
some custom `Objects.yaml` configuration:
```yaml
Some\Vendor\Some\Class:
properties:
'eventPublisher':
object:
factoryObjectName: Neos\EventSourcing\EventPublisher\DefaultEventPublisherFactory
arguments:
1:
value: 'Some-EventStore-Id'
```
> BUGFIX: Make DefaultEventPublisherFactory return the same instance

- Classes/EventListener/EventListenerInvoker.php
- Classes/EventPublisher/JobQueue/CatchUpEventListenerJob.php
- Classes/Projection/ProjectionManager.php
- Tests/Unit/EventListener/EventListenerInvokerTest.php
- Tests/Unit/EventListener/Fixture/AppliedEventsStorageEventListener.php
- composer.json
Previously the whole `EventListenerInvoker::catchup()` call triggered a
single blocking transaction that was only committed when the corresponding
event listener was up to date with the event store.
Especially for replays and initial catchups this posed a problem because
of the ever growing transaction.
With this change the "Highest Applied Sequence Number" is released after
each applied event.
This has the nice side effect that multiple workers can share the load:
While process 1 commits the transaction, process 2 can already start processing
the next event.
For batch-processing the batch size can be increased in order to improve performance:
$eventListenerInvoker = (new EventListenerInvoker($eventStore, $listener, $connection))
->withTransactionBatchSize(500)
->catchup()
This is a …
> !!! BUGFIX: Release "highest applied sequence number" during catchup

- Classes/EventListener/Mapping/DefaultEventToListenerMappingProvider.php
- Resources/Private/Schema/Settings/Neos.EventSourcing.schema.yaml
- Tests/Unit/EventListener/Mapping/DefaultEventToListenerMappingProviderTest.php
With #256 the `DefaultEventToListenerMappingProvider` was introduced
with a very defensive behavior that prevents event store configurations
without matching Listeners.
This was taking it a little far and creates a hen-egg situation for the
initial setup because it requires an `EventListenerInterface` instance
to exist before a store can be configured.
With this change it's allowed to leave out the `listeners` configuration:
```yaml
Neos:
EventSourcing:
EventStore:
stores:
'event-store':
storage: 'Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage'
```
If one is specified it is still validated of course, so the follwing example will lead
to an exception if no EventListener exists yet:
```yaml
Neos:
EventSourcing:
EventStore:
stores:
'event-store':
storage: …
```
> BUGFIX: Relax DefaultEventToListenerMappingProvider checks

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
Fixes a regression introduced with 4ec28d36644acab4b21fc1db50903e6058c8b669 that
led to the `recordedAt` column of published events to miss the time component.
To apply the fix, run
./flow eventstore:setupall
> BUGFIX: Fix recordedAt column type for DoctrineEventStorage

- Classes/Command/ProjectionCommandController.php
- Classes/EventListener/EventListenerInvoker.php
- Classes/EventStore/Storage/InMemory/InMemoryStreamIterator.php
- Classes/Projection/ProjectionManager.php
- Tests/Unit/EventListener/EventListenerInvokerTest.php
- Tests/Unit/EventStore/Storage/InMemory/InMemoryStreamIteratorTest.php
This change introduces a feature which allows for applying events
(catchup / replay) up to a specified event sequence number. Besides
supporting this in the `EventListenerInvoker`, the feature is also
provided by the `projection:replay` and `projection:replayall`
commands which introduce a new flag for this purpose.
Resolves #268
> FEATURE: Replay / catch up until sequence number

- Classes/Command/ProjectionCommandController.php
- Classes/Projection/ProjectionManager.php
- Tests/Unit/Projection/ProjectionManagerTest.php
This change introduces a new CLI command which allows for applying
new events for a given or all projections. It's also possible to
specify the sequence number of an event up to which events should be
applied.
This command is meant to be used for debugging and other rather un-
common needs. In general, events should be applied by other means,
for example through the `CatchUpEventListenerJob`.
Resolves #270
> FEATURE: Introduce projection:catchup command

- Tests/Unit/EventListener/EventListenerInvokerTest.php
- Tests/Unit/EventStore/Storage/InMemory/InMemoryStreamIteratorTest.php
* Add `setUp` return type hint to fix compatibilty with PhpUnit 9+
* Fix "Only arrays and Traversables can be unpacked" error with PHP 7.3
> BUGFIX: Fix unit tests

- Classes/Projection/ProjectionManager.php
When using the projection:catchup CLI command, the respective
projections are reset due to some misplaced code in the Projection
Manager.
Resolves #275 
See also #270
> BUGFIX: Projection is reset on projection:catchup

- Classes/EventPublisher/DeferEventPublisher.php
- Tests/Unit/EventPublisher/DeferEventPublisherTest.php
Previously, consecutive calls to "invoke()" would publish old
events again as the $pendingEvents were never reset.
> BUGFIX: Clear $pendingEvents when invoking DeferEventPublisher

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
When not setting the order by the sorting of the query is not always the primary key depending on the order in the index.
For me as simple category stream query retuned the following order and thats why the projector not getting all events in the correct order:
|sequencenumber|
| ------------- |
|83            |
|63            |
|1018          |
|209           |
|161           |
|1             |
|71            |
|623           |
|59            |
|67            |
|922           |
|178           |
|225           |
> Guaranty order of sequencenumber

- Classes/EventStore/Normalizer/ValueObjectNormalizer.php
The constructor methods for value objects (for example `fromArray()`) are considered by the `ValueObjectNormalizer` when events are unserialized from the event store. However, if a `fromArray()` method is declared with a `static` return type, the method is not considered by the normalizer.
This change adds support for those constructors.
> Allow "static" return type for constructor methods

- Classes/AbstractEventSourcedAggregateRoot.php
- Classes/Event/EventTypeResolver.php
- Classes/EventListener/AppliedEventsStorage/DefaultAppliedEventsStorage.php
- Classes/EventListener/Mapping/EventToListenerMapping.php
- Classes/EventPublisher/DeferEventPublisher.php
- Classes/EventStore/WritableEvents.php
binding is used and corrects `new static` to `new self` in classes
declared as `final`.
*Exceptions:* For `DeferEventPublisher` and `DefaultAppliedEventsStorage` the
class name itself is used in order to prevent IDEs to complain about the use
of `static` in a final class. Those classes currently rely on Flow object
management so `self` refers to the proxy class
Resolves #309
> This change corrects return types to "static" where late static

- Classes/EventListener/EventListenerInvoker.php
While catching up or replaying a projection, a transaction for the highest applied event sequence number is only closed when an event was actually applied or the catch-up-process is done. This speeds up the process dramatically for event stores containing hundreds of thousands of events.
Two examples:
1) Event store with 2.000.000 events. Only 3500 are relevant for the projection in question. Replaying the projection takes
- 6 minutes 22 seconds without the patch
- 0 minutes 50 seconds with the patch
2) Event listener lags 50.000 events behind. Only 1 new relevant event for the projection. Catching up takes
- 87100 milliseconds without the patch
-  1200 milliseconds with the patch
Resolves #316
> Speed up catchUp() and replay()
