neos/Neos.EventSourcing

- Classes/EventListener/EventListenerLocator.php
This change the event listener prefix from ```on``` to ```when```
Closes #16
> TASK: EventListener methods should be prefixed by when

- Classes/Domain/AggregateRootTrait.php
> TASK: Event handler methods in aggregates should be optional

- Classes/Domain/AbstractAggregateRoot.php
> TASK: AggregateRoot: remove trait in favour of base class

- Classes/Command/EventStoreCommandController.php
- Classes/Domain/AbstractEventSourcedAggregateRoot.php
- Classes/Domain/EventSourcedAggregateRootInterface.php
- Classes/Event/Metadata.php
- Classes/EventStore/EventSourcedRepository.php
- Classes/EventStore/EventStore.php
- Classes/EventStore/EventStoreInterface.php
- Classes/EventStore/EventStream.php
- Classes/EventStore/EventStreamData.php
- Classes/EventStore/Exception/ConcurrencyException.php
- Classes/EventStore/Exception/EventStreamNotFoundException.php
- Classes/EventStore/Storage/Doctrine/DataTypes/DateTimeType.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/Storage/Doctrine/Factory/ConnectionFactory.php
- Classes/EventStore/Storage/Doctrine/Schema/EventStoreSchema.php
- Classes/EventStore/Storage/EventStorageInterface.php
- Classes/Serializer/ArraySerializer.php
- Classes/Serializer/JsonSerializer.php
- Configuration/Objects.yaml
- Configuration/Settings.yaml
Temporarily merge the packages `Neos.EventStore` and
`Neos.EventStore.DatabaseStorageAdapter` into this package to ease development.
Resolves: #32
> TASK: Merge EventStore packages into Cqrs package

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
This fixes an issue with updating aggregates: the version number
wasn't increased.
> BUGFIX: Version is not increased for stream on update

- Classes/Command/ProjectionCommandController.php
- Classes/Projection/ProjectionManager.php
This cleans up the `ProjectionCommandController` a bit and
provides a way to replay events for all existing projections.
Related to #47
> TASK: Improve projection:replay command

- Classes/Command/ProjectionCommandController.php
Usage:
flow projection:watch some:projection
This will poll new events for the given projection every 10 seconds.
With the optional `poll-interval` argument that interval can be changed.
Related: #37
> FEATURE: "projection:watch" CLI command

- Readme.md
For easier config, add a documentation chapter about setting up the DB connection for this package.
> TASK: Add a DB config chapter to README

- Classes/Command/EventStoreCommandController.php
This change improves the CLI commands for schema creation and
displaying the connection status.
The `eventstore:createschema` command will now check if the given
event stream table already exists and if it does, displays a friendly
message instead of failing impolitely.
The `evenstore:status` command will now display which tables is
configured for the event stream and if that table exists.
> FEATURE: Improved schema creation and connection status

- Classes/Event/EventTypeResolver.php
- Classes/ProcessManager/AbstractProcessManager.php
- Classes/ProcessManager/State/ProcessState.php
- Classes/ProcessManager/State/StateRepository.php
- Classes/Projection/Doctrine/AbstractDoctrineProjector.php
- Classes/Projection/Doctrine/DoctrineProjectionPersistenceManager.php
- Classes/Projection/Projection.php
- Classes/Projection/ProjectionManager.php
Added some missing type hints and fixed a few IDE warnings
> TASK: Improve type hints

- Classes/TypeConverter/EventToArrayConverter.php
- Tests/Unit/TypeConverter/EventToArrayConverterTest.php
- Tests/Unit/TypeConverter/Fixtures/EventWithDates.php
- Tests/Unit/TypeConverter/Fixtures/EventWithJsonSerializableProperties.php
- Tests/Unit/TypeConverter/Fixtures/EventWithObjects.php
- Tests/Unit/TypeConverter/Fixtures/EventWithSimpleTypes.php
- Tests/Unit/TypeConverter/Fixtures/JsonSerializableEvent.php
> FEATURE: Support JsonSerializable events and event properties

- Classes/Domain/AbstractAggregateRoot.php
- Classes/Event/EventTypeResolver.php
- Classes/EventListener/EventListenerLocator.php
- Classes/EventStore/EventStore.php
- Classes/EventStore/EventStreamFilterInterface.php
- Classes/EventStore/EventTypesFilter.php
- Classes/EventStore/StreamNameFilter.php
- Classes/ProcessManager/AbstractAsynchronousProcessManager.php
- Classes/Projection/AbstractBaseProjector.php
- Classes/Projection/Doctrine/AbstractAsynchronousDoctrineProjector.php
- Classes/Projection/InvalidProjectionIdentifierException.php
- Classes/Projection/Projection.php
Just a cosmetic change removing all unused `import` statements
> TASK: Remove unused namespace imports

- Classes/EventStore/StreamNamePrefixFilter.php
Adds a filter for an event stream to filter by stream name prefix. The implementation already supports this, but there was no filter implementation in this package so far.
> FEATURE: Add stream name prefix event stream filter implementation

- Classes/EventStore/EventIdentifierFilter.php
- Classes/EventStore/EventStreamFilterInterface.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
Adds a new EventStream filter `EventIdentifierFilter` that allows
for matching against the event identifier.
This allows to fetch single events from the EventStore:
$eventStore->get(new EventIdentifierFilter($identifier))->current();
Related: #164
> FEATURE: EventIdentifier Stream filter

- Classes/EventStore/EventStore.php
- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
- Classes/EventStore/Storage/EventStorageInterface.php
this is needed for the event sourced CR
> FEATURE: allow to retrieve current stream version

- Classes/Command/ProjectionCommandController.php
> BUGFIX: Add missing newline in batch replay after the progress bar

- Classes/Event/Decorator/EventDecoratorUtilities.php
- Classes/Event/Decorator/EventWithIdentifier.php
- Classes/Event/Decorator/EventWithMetadata.php
- Classes/Event/DomainEvents.php
- Classes/EventBus/EventBus.php
- Classes/EventListener/AppliedEventsLogRepository.php
- Classes/EventStore/EventStore.php
- Classes/Projection/ProjectionManager.php
- Configuration/Testing/Behat/Settings.yaml
@bwaidelich a full bunch of fixes, please review them commit by commit (and see the commit descriptions for proper explanations)
> Decorators async handling appliedeventslog fixes

- Readme.md
TODO: Retrieve the eventStore according to the stream name from eventStoreManager
> TASK: Update README with section on how to create a Repository

- Classes/EventListener/AppliedEventsLogRepository.php
- Tests/Functional/EventListener/AppliedEventsLogRepositoryTest.php
> BUGFIX: Fix PostgreSQL support

- Classes/EventStore/EventNormalizer.php
- Classes/EventStore/Normalizer/ProxyAwareObjectNormalizer.php
- Tests/Functional/EventStore/EventNormalizerTest.php
- Tests/Functional/EventStore/Fixture/MockDomainEvent.php
- Tests/Functional/EventStore/Fixture/MockDomainEvent2.php
> BUGFIX: Fix support for Flow proxy classes

- Classes/Event/DecoratedEvent.php
Otherwise they can't be serialized properly
> BUGFIX: Don't proxy DecoratedEvents

- Classes/EventStore/Storage/Doctrine/DoctrineEventStorage.php
Previously only DBALExceptions and ConcurrencyException would cause a rollback, while all other exceptions would keep the transaction open. Also, this had the rollback in the case of a ConcurrencyException hidden inside the `verifyExpectedVersion` method.
See https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/transactions.html#transactions
Also, this prevents leaving a transaction open, if another one has already been started before.
> BUGFIX: Correctly roll back transaction for all errors

- Classes/ProcessManager/State/StateRepository.php
> BUGFIX: Fix support for recent doctrine versions

- Glossary.md
- Readme.md
- Tutorial.md
> FEATURE: Initial Documentation

- Readme.md
> Remove broken ProductRepository::create() example from Readme

- Classes/EventListener/Mapping/EventToListenerMapping.php
- Classes/EventListener/Mapping/EventToListenerMappings.php
- Classes/EventStore/EventStream.php
- Classes/EventStore/Storage/InMemory/InMemoryStreamIterator.php
At least unit tests should pass with these adjustments.
> Adjust a few return types for PHP 8.1

- Classes/EventListener/AfterCatchUpInterface.php
- Classes/EventListener/AppliedEventsStorage/AppliedEventsStorageInterface.php
- Classes/EventListener/EventListenerInvoker.php
- Readme.md
This is an alternative implementation of https://github.com/neos/Neos.EventSourcing/pull/303 after discussion :)
> FEATURE: AfterCatchUpInterface and documentation on how to trigger side effects after projection update

- composer.json
Based on the current state, this package does work with Flow 9.0 dev.
> TASK: Declare compatibility with Flow 9
